# Generated by Django 5.0.6 on 2024-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('fees', models.FloatField()),
                ('appointment_date', models.CharField(max_length=10)),
                ('appointment_time', models.CharField(max_length=10)),
            ],
        ),
    ]
